### ISSUE TITLE
Most recent version breaks system

### ISSUE THREAD

**Issue by spaceman7777** [slyfox1186/ffmpeg-build-script#33] opened 2024-05-20 05:37 UTC
Hey, I've been using your script this month, and pulled down the latest version a few days ago..

and, idk what happened.. but it has absolutely wrecked my system.

this is what's at / right now... please fix. I need to figure out what in the world happened now and try to fix my system, because this is really really bad.
![Selection_1697](https://github.com/slyfox1186/ffmpeg-build-script/assets/122674880/83ee5a0a-92ac-44bf-b054-f047e42e8983)

**Comment by spaceman7777** [comment] 2024-05-20 05:49
If I were to guess, it's due to this change here overwriting the global packages variable. It's not quite as bad as I thought... probably... but I absolutely flipped when I saw this.

System is probably reparable.

As extra info, this is running on ubuntu 23.10 via zsh 5.9.

I noticed the issue while investigating a build failure in libbluray.

options I was running with are: `./build-ffmpeg.sh -b -l -n --compiler=gcc`


![Selection_1698](https://github.com/slyfox1186/ffmpeg-build-script/assets/122674880/63cae4b7-b9e7-4484-9f78-d3d11e698cfc)

**Comment by rharmonson** [comment] 2024-05-20 23:00
This is a duplicate of https://github.com/slyfox1186/ffmpeg-build-script/issues/31

**Comment by slyfox1186** [comment] 2024-05-23 16:12
Sorry I was sick in bed. I will fix this. Give me a second here.

What version broke your system?

What version did you have before that worked?

**Comment by slyfox1186** [comment] 2024-05-23 17:43
This should be fixed in version 3.8.0. I have tested the script on Windows WSL and Native Ubuntu 24.04.

The apt_pkgs function had unfortunate coding in it and I will be very cautious going forward regarding the this type of command. I believe this is what lead to the issues you have experienced.

I hope this resolves everything and I am sorry about the inconvenience it caused you downloading things to an incorrect directory.

If there are any other issues let me know and thank you very much for reporting.

Also, GCC is the default compiler. No need to specify it unless you want to.

**Closed as completed by slyfox1186** 2024-05-23 17:43 UTC

**Comment by rharmonson** [comment] 2024-05-23 19:18
Thank you!
