### ISSUE TITLE
Debian 12: FFMPEG and [ERROR] Failed to execute make -j4

### ISSUE THREAD

**Issue by rharmonson** [slyfox1186/ffmpeg-build-script#34] opened 2024-05-23 22:37 UTC
commit 5fbe8bf

When attempting to build using `-b` or `-b -n` or `-b -n -l`, everything goes well until compiling ffmpeg. Here is an example of the output.

Error:

```
License: nonfree and unredistributable
$ make -j4

[ERROR] Failed to execute make -j4

[INFO] For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues
```

Attaching the complete build output.
[ffmpeg-make-error.txt](https://github.com/slyfox1186/ffmpeg-build-script/files/15424664/ffmpeg-make-error.txt)

System info:
[system.txt](https://github.com/slyfox1186/ffmpeg-build-script/files/15424691/system.txt)

**Comment by slyfox1186** [comment] 2024-05-24 00:14
cd into `master-folder-here/packages/ffmpeg-NUMBERS_HERE/build`
`clear` the screen
run `sudo make -j4`
if that is successful
run `sudo make install`

Copy the output in terminal and send my way again.

**Comment by rharmonson** [comment] 2024-05-24 02:02
```
~/r/t/ffmpeg-build-script/packages/ffmpeg-n7.0🔒 ❯ sudo make -j4
Makefile:194: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
```
screenshot:
![ffmpeg-make](https://github.com/slyfox1186/ffmpeg-build-script/assets/7966126/ae4c8cc4-fd2f-41fc-9065-b31e3d162b40)

**Comment by slyfox1186** [comment] 2024-05-24 03:06
You didn't go to the build directory. you stopped at `ffmpeg-n7.0`.
cd into the `ffmpeg-n7.0/build`.

Also, I updated the script a few minutes ago. Make sure you grab that version so we are all on the same exact page.

**Comment by slyfox1186** [comment] 2024-05-24 03:34
Update:

I too am having issues with installing FFmpeg 7.0 on Debian 12 so I reverted all Debian installs to version 6.1.1 for now.

You are welcome to share you build logs with me and I will still take a look to see if I see anything worthwhile.

Regardless, let's hope version 7.1.1 fixes some issues.

**Comment by rharmonson** [comment] 2024-05-24 04:16
You are correct. I failed to enter the build directory. Apologies.

I need ffmpeg 7 binaries and libraries, unfortunately. The libraries to build against--not looked at how to do that activity, yet.

> You are welcome to share you build logs with me and I will still take a look to see if I see anything worthwhile.

Happy to attach the logs. I am rather new to this stuff. Where are the logs?

**Comment by rharmonson** [comment] 2024-05-24 04:24
Is this the issue you observed for commit https://github.com/slyfox1186/ffmpeg-build-script/commit/5fbe8bf0c89dc3e1cc1ea162a0aa377ffb4496cb?

```
~/r/t/f/packages/ffmpeg-n7.0/build🔒 ❯ sudo make -j4
LD	ffmpeg_g
/usr/bin/ld: /home/user/repos/temp/ffmpeg-build-script/workspace/lib/libbluray.a(libbluray_la-dec.o): in function `dec_init':
dec.c:(.text+0x280): multiple definition of `dec_init'; fftools/ffmpeg_dec.o (symbol from plugin):(.text+0x0): first defined here
lto-wrapper: warning: using serial compilation of 128 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
/usr/bin/ld: warning: libx265.so.199, needed by /lib/x86_64-linux-gnu/libavcodec.so.59, may conflict with libx265.so.209
collect2: error: ld returned 1 exit status
make: *** [/home/user/repos/temp/ffmpeg-build-script/packages/ffmpeg-n7.0/Makefile:136: ffmpeg_g] Error 1
```

**Comment by slyfox1186** [comment] 2024-05-24 06:13
> Is this the issue you observed for commit [5fbe8bf](https://github.com/slyfox1186/ffmpeg-build-script/commit/5fbe8bf0c89dc3e1cc1ea162a0aa377ffb4496cb)?
> 
> ```
> ~/r/t/f/packages/ffmpeg-n7.0/build🔒 ❯ sudo make -j4
> LD	ffmpeg_g
> /usr/bin/ld: /home/user/repos/temp/ffmpeg-build-script/workspace/lib/libbluray.a(libbluray_la-dec.o): in function `dec_init':
> dec.c:(.text+0x280): multiple definition of `dec_init'; fftools/ffmpeg_dec.o (symbol from plugin):(.text+0x0): first defined here
> lto-wrapper: warning: using serial compilation of 128 LTRANS jobs
> lto-wrapper: note: see the ‘-flto’ option documentation for more information
> /usr/bin/ld: warning: libx265.so.199, needed by /lib/x86_64-linux-gnu/libavcodec.so.59, may conflict with libx265.so.209
> collect2: error: ld returned 1 exit status
> make: *** [/home/user/repos/temp/ffmpeg-build-script/packages/ffmpeg-n7.0/Makefile:136: ffmpeg_g] Error 1
> ```

Yes, these are the errors. Funny how it is almost identical across distros.

I will close this for now and if anything else pops up let me know.

Again, reporting is awesome and it sometimes is the first way I learn of issues so thanks for this.

**Closed as completed by slyfox1186** 2024-05-24 06:13 UTC

**Comment by rharmonson** [comment] 2024-05-24 16:00
Above you referenced a ffmpeg build log. For future issues, where is it located?

I want to verify my understanding of your post above. We are waiting for a new upstream release in hopes the ffmpeg 7 dependency conflict is fixed?

**Comment by slyfox1186** [comment] 2024-05-24 19:11
I am waiting unless you have a better idea of how to fix this so version 7.0 builds successfully. At the moment, downgrading to 6.1.1 fixed my issue and was good enough for me right now.

Supporting multiple distros is not easy lol.

**Comment by rharmonson** [comment] 2024-05-24 19:15
I totally understand and not unhappy. I will set aside a couple hours to research and fuss with it.

Log.. my question on the ffmpeg log above. where?

**Comment by slyfox1186** [comment] 2024-05-24 23:20
Sorry I skipped your log question.

There is no log file. The best you will do for troubleshooting FFmpeg is to open the file config.log.

A lot of failures happen at the end of this file HOWEVER there can be clues all over the file in different places that lead you to where the issue is ultimately coming from. So use this file to help you troubleshoot if you are going to mess with it (I highly recommend getting your feet wet... no better way to learn something).

You can find this file in most repos that use the make command to build and install their source code.

Here is the exact path for this on my computer. Use it to locate the file and jump in! Good luck! Let me know if you figure anything out and I will update the script accordingly.

```bash
cd ffmpeg-build-script/packages/ffmpeg-n6.1.1/build/ffbuild
sudo nano config.log
```

**Comment by rharmonson** [comment] 2024-05-25 19:12
Thank you for the log information. Looking through it now. Helpful!
